-- 가격대별 상품 개수 구하기
-- 1) 금액 단위를 맞추기 위해서 단위에 맞게 나누고 버리고 다시 곱해주기
/*
SELECT FLOOR(PRICE/10000) * 10000 AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY FLOOR(PRICE/10000)
ORDER BY PRICE_GROUP;
*/

-- 2) 버림 활용하기
SELECT TRUNCATE(PRICE, -4) AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNCATE(PRICE, -4)
ORDER BY PRICE_GROUP;
