
/*
SELECT M.MEMBER_NAME, 
       R.REVIEW_TEXT, 
       DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE 
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW R
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)   
        FROM (
            SELECT COUNT(*) AS CNT
            FROM REST_REVIEW R
            GROUP BY MEMBER_ID ) MAX_COUNT
    ))
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
*/





SELECT M.MEMBER_NAME, 
       R.REVIEW_TEXT, 
       DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE 
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
  -- 1. 리뷰 가장 많이 작성한 ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW R
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        -- 2. 가장 많은 리뷰 수
        SELECT COUNT(*)
        FROM REST_REVIEW R
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ))
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
