-- 조건에 맞는 사용자 정보 조회하기 : 문자열 연결하기
/*SELECT U.USER_ID, U.NICKNAME,
 CONCAT(U.CITY, " ", U.STREET_ADDRESS1 ," ", U.STREET_ADDRESS2) AS '전체주소',
 CONCAT(LEFT(TLNO, 3), "-", SUBSTR(TLNO, 4,4), "-", RIGHT(TLNO, 4)) AS "전화번호"
FROM USED_GOODS_BOARD G
INNER JOIN USED_GOODS_USER U
ON G.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(G.BOARD_ID) >= 3
ORDER BY U.USER_ID DESC;*/

-- 조건에 맞는 사용자 정보 조회하기 : 서브쿼리로 조건에 맞는 데이터 먼저 추출하고 조인하기
SELECT U.USER_ID, U.NICKNAME,
 CONCAT(U.CITY, " ", U.STREET_ADDRESS1 ," ", U.STREET_ADDRESS2) AS '전체주소',
 CONCAT(LEFT(TLNO, 3), "-", SUBSTR(TLNO, 4,4), "-", RIGHT(TLNO, 4)) AS "전화번호"
FROM USED_GOODS_USER U
INNER JOIN 
    (SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(BOARD_ID) >= 3) AS G
ON G.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC;