-- 기존 코드 : 문자열로 비교함
/*SELECT  CAR_ID,
    MAX(CASE WHEN DATE("2022-10-16") BETWEEN START_DATE AND END_DATE
        THEN "대여중"
    ELSE "대여 가능" END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;*/


SELECT CAR_ID,
CASE WHEN MAX(
    CASE WHEN DATE("2022-10-16") BETWEEN START_DATE AND END_DATE
        THEN 1
    ELSE 0 END ) = 1 THEN "대여중" ELSE "대여 가능" END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

