-- 코드를 입력하세요

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BS.CATEGORY, SUM(BS.TOTAL_SALES) AS SALES
FROM AUTHOR AS A
INNER JOIN (
    SELECT B.BOOK_ID, CATEGORY, AUTHOR_ID, SALES*PRICE AS TOTAL_SALES
    FROM BOOK B
    INNER JOIN(
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
    GROUP BY BOOK_ID) AS S
    ON B.BOOK_ID = S.BOOK_ID) AS BS
ON BS.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID, BS.CATEGORY DESC;
