-- 조건절 활용하기 : 날짜, 결측치, 특정 데이터만 추출하기
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE (MONTH(DATE_OF_BIRTH) = 3) 
    AND (GENDER = "W")
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;