-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", G.BOARD_ID,"/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT)        AS FILE_PATH
FROM USED_GOODS_BOARD G

INNER JOIN USED_GOODS_FILE F
ON G.BOARD_ID = F.BOARD_ID

WHERE G.VIEWS = (SELECT MAX(VIEWS)
              FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;