-- 코드를 입력하세요
SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
FROM REST_INFO R1
INNER JOIN (
  SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
  FROM REST_INFO
  GROUP BY FOOD_TYPE) R2
ON R1.FOOD_TYPE = R2.FOOD_TYPE  -- 이렇게 2개 모두 조인 조건으로 걸어줘야 함!
AND R1.FAVORITES = R2.MAX_FAVORITES
ORDER BY R1.FOOD_TYPE DESC


/*  서브상관쿼리 버전
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
WHERE FAVORITES = (SELECT MAX(FAVORITES)
    FROM REST_INFO
    WHERE FOOD_TYPE = R.FOOD_TYPE
    -- GROUP BY FOOD_TYPE  <- 이게 필요 없는 이유는, 바깥 쿼리 행에서 조건에 맞는(푸드타입이 같은) 데이터 중 최댓값을 가져올테니 굳이 그룹화 안해도 됨.
    )
ORDER BY FOOD_TYPE DESC
*/