-- 조건에 맞는 사용자와 총 거래금액 조회하기 : WHERE과 HAVING 구분하기
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS "TOTAL_SALES"
FROM USED_GOODS_USER U
INNER JOIN USED_GOODS_BOARD B
ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = "DONE"
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY 3;