-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
        IFNULL(FREEZER_YN, "N") AS FREEZER_YN -- NULL일때만 뒤 값 출력하기

/* 조건문
    CASE 
        WHEN FREEZER_YN IS NULL THEN "N"
        WHEN FREEZER_YN = "N" THEN "N"
        ELSE "Y"
        END AS FREEZER_YN*/
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "경기도%"
ORDER BY WAREHOUSE_ID ASC;